import asyncio
import random
from typing import List
from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from sqlalchemy.orm import Session


from app.db.session import get_db
from app.models.user import User
from app.models.image import ImageGeneration, GenerationStatus
from app.schemas.image_generations import GenerationResponse
from app.services.storage_service import StorageService
from app.api.deps import get_current_user

router = APIRouter()


@router.post("/create")
async def create_generation(
    prompt: str = Form(...),
    self_image: UploadFile = File(...),
    target_image: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    storage = StorageService()

    # 1. Validation (Fail Fast)
    if not prompt or len(prompt) < 3:
        raise HTTPException(status_code=400, detail="Prompt too short")

    try:
        # 2. Upload Images to Supabase (Parallel Execution possible, but sequential is safer for now)
        self_url = await storage.upload(self_image, folder="inputs")
        target_url = await storage.upload(target_image, folder="targets")

        # 3. Create Database Record (Status: PENDING)
        db_gen = ImageGeneration(
            user_id=current_user.id,
            prompt=prompt,
            self_image_url=self_url,
            target_image_url=target_url,
            status=GenerationStatus.PROCESSING,
        )
        db.add(db_gen)
        db.commit()
        db.refresh(db_gen)

        # 4. MOCK AI PROCESS (Replace this with real API call later)
        # Simulate processing time
        await asyncio.sleep(2)

        # Mock result
        mock_seed = random.randint(100, 999)
        output_url = f"https://picsum.photos/seed/{mock_seed}/512/512"

        # 5. Update Record (Status: COMPLETED)
        db_gen.output_image_url = output_url
        db_gen.status = GenerationStatus.COMPLETED
        db.commit()

        return {
            "id": db_gen.id,
            "status": "completed",
            "output_url": output_url,
            "self_url": self_url,
            "target_url": target_url,
        }

    except Exception as e:
        # If anything fails, try to mark as failed in DB
        if "db_gen" in locals():
            db_gen.status = GenerationStatus.FAILED
            db.commit()
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/history", response_model=List[GenerationResponse])
def get_user_history(
    skip: int = 0,
    limit: int = 20,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Fetch the list of images generated by the logged-in user.
    Ordered by newest first.
    """
    all_generations = (
        db.query(ImageGeneration)
        .filter(ImageGeneration.user_id == current_user.id)
        .order_by(ImageGeneration.created_at.desc())
        .offset(skip)
        .limit(limit)
        .all()
    )

    return all_generations
