"""add target image column

Revision ID: 3c3fd4cb5f63
Revises: b83151ee9457
Create Date: 2025-12-16 22:07:22.423898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3fd4cb5f63'
down_revision: Union[str, Sequence[str], None] = 'b83151ee9457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generations', sa.Column('self_image_url', sa.String(), nullable=False))
    op.add_column('image_generations', sa.Column('target_image_url', sa.String(), nullable=False))
    op.drop_column('image_generations', 'input_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generations', sa.Column('input_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('image_generations', 'target_image_url')
    op.drop_column('image_generations', 'self_image_url')
    # ### end Alembic commands ###
