"""user_image_table_created

Revision ID: 6399a6e4bc86
Revises: 
Create Date: 2025-12-19 16:03:36.133979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6399a6e4bc86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('google_id', sa.String(length=300), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('profile_picture', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('imagegenerations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('self_image_url', sa.String(length=500), nullable=False),
    sa.Column('target_image_url', sa.String(length=500), nullable=True),
    sa.Column('generated_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagegenerations_id'), 'imagegenerations', ['id'], unique=False)
    op.create_index(op.f('ix_imagegenerations_user_id'), 'imagegenerations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagegenerations_user_id'), table_name='imagegenerations')
    op.drop_index(op.f('ix_imagegenerations_id'), table_name='imagegenerations')
    op.drop_table('imagegenerations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
